DEFAULT_FOLDER = lko_crkbd/rev1
SRC += keymap.c
MOUSEKEY_ENABLE = yes     # Mouse keys
VIA_ENABLE      = yes    # Enable VIA
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes
